Vagrant.configure("2") do |config|
  config.vm.hostname = "Prism-Redis-Service"

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.synced_folder "../redis", "/home/vagrant/redis", create: true

  config.vm.provision "docker"
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  # Port forwarding to host machine
  config.vm.network :forwarded_port, host: 6379, guest: 6379 #redis
  #config.vm.network :forwarded_port, host: 3306, guest: 3306 #mysql
  #config.vm.network :forwarded_port, host: 8081, guest: 8081 #app (for container test)
end
